# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Echart_ios' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Echart_ios
  pod 'iOS-Echarts’

end
